replicaCount: 1

image:
  repository: postgres
  tag: "15"
  pullPolicy: IfNotPresent

service:
  name: postgres
  type: ClusterIP
  port: 5432 
  
serviceAccount:
  create: true
  name: "vault"

storage:
  size: 5Gi

postgresUser: vault
postgresPassword: vaultpassword
postgresDatabase: vaultdb

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: postgres.example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
