apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: vault
spec:
  serviceName: "postgres"
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: POSTGRES_USER
          value: "{{ .Values.postgresUser }}"
        - name: POSTGRES_PASSWORD
          value: "{{ .Values.postgresPassword }}"
        - name: POSTGRES_DB
          value: "{{ .Values.postgresDatabase }}"
        ports:
        - containerPort: {{ .Values.service.port }}
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.storage.size }}
